version: '3.8'

services:
  app:
    build: .
    container_name: jobts-app
    network_mode: "host"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      LLM_PROVIDER: ${LLM_PROVIDER}
      GPT_API_KEY: ${GPT_API_KEY}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
    ports:
      - "8082:8082"
