server:
  port: 8082

spring:
  servlet:
    multipart:
      enabled:true
      max-file-size:50MB
      max-request-size:100MB
  application:
    name: jobts.be
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
  expiredDay: 86400000
